### PR TITLE
fix: updates rules.Store memory to merged extracted rules and checks

### LINKED ISSUE #46: Bug: rules.MemoryStore overwrites indexed rules and checks for components with the same title
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When indexing multiple validation components with the same title with the `rules.MemoryStore`, the only component data the is preserved is the last to be indexed.

### Expected Behavior

If a component is cataloged with the same title, the rules are merged instead of overwritten. This is required for use cases where a validation component with multiple target components.

### Steps To Reproduce

1. Create two component definitions with different target components, but the same validation component. Add different rules.
2. Read the component definitions and indexed them with `rules.Store.IndexAll`
3. Observe that the second component definition data passed in is reflected and the first component definition data is not there.

### Environment

```markdown
- OS: Fedora
- Go Version: 1.23
- Platform: linux/amd64
```

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by jpower432**
## Description

Updates `rules.MemoryStore` indexing behavior to merge rules and checks instead of keeping the last indexed component data preserved. 

Fixes #46 

## How has this been tested?

- [X] Unit tests and test data added to cover use case

## Types of changes

- [ ] Hot fix (emergency fix and release)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation (change which affects the documentation site)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Quality assurance (all should be covered).

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [x] All commits are signed-off.

### CODE REVIEW

**Review by gvauter — APPROVED** [review]
LGTM

File: rules/memory_test.go [hunk 1]
```diff
@@ -166,24 +167,48 @@ func TestMemoryStore_FindByComponent(t *testing.T) {
 
 	_, err = testMemory.FindByComponent(testCtx, "not_a_component")
 	require.EqualError(t, err, "failed to find rules for component \"not_a_component\"")
+
+	// Add a new target component for ="Validator"
```
Comment (marcusburghardt) [inline rules/memory_test.go:171]:
```suggestion
	// Add a new target component for "Validator"
```
Really a nit : )

**Review by marcusburghardt — APPROVED** [review]
LGTM. Thanks for fixing this.
